const UOM_LIST = ["BDL", "BOX", "CAD", "CS", "EA", "HNK", "KG", "L", "LB", "RCK", "RL"];
const CATEGORY_LIST = [
      "Berkshire Chris",
      "Box",
      "Chemical Room",
      "Container Product",
      "Cooler Remake Chris",
      "Dry Storage",
      "Finished Goods",
      "Freezer Products",
      "Freezer Random & Seconds & Code Dated Product (Chris)",
      "Ingredients Processing Room Chad",
      "Ingredients Smokehouse Chad",
      "Ingredients Spice Room",
      "Labels",
      "Markey Hog Cuts Chad",
      "Meat WIP Chad",
      "NRTE Cooler",
      "Other Products Freezer Chris",
      "Packaging Boning Shipping Office",
      "Packaging Office, ShippingRack Chad",
      "Packaging Offiste, Storage Trailer",
      "Packaging ShipOff, Cooler, Dock",
      "Plain Bags",
      "Printed Bags",
      "Roll Stock",
      "Samples",
      "Short Code Cooler",
      "Short Code Freezer",
      "WIP Carcass Cooler Chad",
      "WIP Freezer Chris",
      "WIP Other Locations",
      "WIP Smoke & Pkg Cooler"
    ];


const LOCATION_LIST = [
  "CHEMICAL ROOM",
  "DRY STORAGE",
  "FREEZER",
  "NRTE",
  "NRTE COOLER",
  "PROCESSING COOLER",
  "RTE",
  "SHIPPING",
  "SMOKEHOUSE",
  "SPICE ROOM",
  "TRAILER",
];
